### ISSUE TITLE
support pug

### ISSUE THREAD

**Issue by johnnonolan** [opentable/oc#398] opened 2017-03-08 22:01 UTC
![image](https://cloud.githubusercontent.com/assets/101177/23726034/a7a1543c-0407-11e7-9db4-25964d97c649.png)

**Comment by matteofigus** [comment] 2017-03-08 22:21
Love the image, but closing as this is a duplicate of #298 

It is low priority, but if this is blocking you, we can try to prioritise this @johnnonolan

**Closed by matteofigus** 2017-03-08 22:21 UTC

**Comment by johnnonolan** [comment] 2017-03-09 21:53
@matteofigus it's not high - just a wish.
