### ISSUE TITLE
Not able to serve gzip version of static resources over OC

### ISSUE THREAD

**Issue by NapoleanReigns** [opentable/oc#526] opened 2017-06-28 18:41 UTC
I am trying to serve gzip versions of static resources (javascript and css files) in my index.html over OC and it does not seem to quite pick up/serve the gzip versions of the file. 

Considering the advantages of serving gzip versions of files (Javascript/css etc), i think it is one of the must have features that every front end developer would like to have in his project.

Kindly share your thoughts.

**Comment by NapoleanReigns** [comment] 2017-06-28 18:47
Not sure if i have done a good job on articulating the problem properly in above comments,
For Example:

If i have a link tag in my template.html as below,
<link rel="stylesheet" type="text/css" href="{{path}}css/sample.css"/>

and if my s3 Bucket has below files available,
css/sample.css
css/sample.cssgz (gzipped file)

Does OC retrieve the gzipped version of the file. ?

**Comment by matteofigus** [comment] 2017-06-28 18:49
Uhm, I think OC automatically handles css.gz and js.gz. Maybe the problem is that you are using the cssgz extension.

Tests: https://github.com/opentable/oc/blob/9f0d07b6c22f4331b2e6a7c02dfab3ff66c39c04/test/unit/utils-get-file-info.js#L25-L55

**Comment by NapoleanReigns** [comment] 2017-06-28 18:51
I did try out one workaround on this,

i uploaded the gzipped version of the file on s3 Bucket with below configuration and it retrieved the gzipped version of the file for me,
Content Type: text/javascript
Content Encoding: gzip

But ideally in a environment where a web server is used to serve static resources, the server configuration would take care of compression and retrieves the gzipped version of the resource if already compressed.

Am i missing anything over here ??

**Comment by matteofigus** [comment] 2017-06-28 19:06
Ok ok, let me clarify.

The test I linked is to show that if you have a build pipeline for making a css.gz file yourself and you put it in the static asset folder, that will be uploaded and when referenced from markup, it should work.

On the other hand, that is something that we have in our codebase from the old ages (when the cli allowed you to automatically do the gzipping) and we stopped supporting it. The reason, is that we found out it's much simpler to delegate such things to a CDN that sits on top of S3.

In our case and most of the people using OC in prod, a CDN is necessary anyways to distribute the content in multiple regions, and modern CDNs like akamai or cloudfrount (which you can setup very easily on top of your s3 account) support http2, which gzips all by default.

So, the way we do this in production, we setup the cdn url on top of oc configuration for OC (which almost serves as a proxy on top of S3) and then we just reference the resources with the real extensions. The cdn will take care of serving gzip if the browser supports, and do all the magic for us.

I hope it makes sense. Are you planning to use a CDN on top of your S3 account?

**Comment by NapoleanReigns** [comment] 2017-06-28 19:09
> I hope it makes sense. Are you planning to use a CDN on top of your S3 account?

Not anytime soon :(
Are there any better workarounds ??

**Comment by matteofigus** [comment] 2017-06-28 19:27
So, let's go back a couple of steps.
You have a .css file, and you are referencing it in your component, correct?
My question is. If you manually gzip it, and then reference it as my-file.css.gz in your component's markup,
1) does it work on dev?
2) does it work when published?

Because if we establish that it works, than the best workaround is to setup a task that does the gzipping automatically with a watcher or something like that. If it doesn't work, we may have some issues to fix here.

**Comment by NapoleanReigns** [comment] 2017-07-10 12:44
One pre-requisite functionality that needs to be there in oc for any of the approaches mentioned above to work, is the ability to set the metadata parameters (content-encoding and content-type) of the files/folders that get uploaded into s3 bucket with oc publish.

Of course there is a workaround for this - a user can manually do it in s3 bucket. 
I am thinking about the production environment here.

Any thoughts ??

**Comment by matteofigus** [comment] 2017-07-10 12:58
@NapoleanReigns the current strategy is to delegate this to automation by following some conventions. Any filename ending in .gz has content-encoding set to gzip and the content-type is defined by its extension (for instance .css.gz gets 'text/css').

This is why I asked in my previous comment if you could do that attempt and tell me if that works. I think conventions make life easier as they bring simplicity to the table, with inherited consistency.

**Comment by NapoleanReigns** [comment] 2017-07-28 13:56
Hey @matteofigus sry for getting back late on this one, was pretty held up with other tasks.

I tried the above,
1) Compressed (pretty huge) javascript files with extension .js.gz
2) Referred the same in my import statements with same extension .js.gz

and it worked. :) 

Awesome. Thanks

**Comment by matteofigus** [comment] 2017-07-28 15:08
Cool stuff. Is it anything else we can do, or should we close this issue?

**Comment by NapoleanReigns** [comment] 2017-07-30 19:10
I think we can close this issue, unless we want to keep this open for discussion to address other possibilities/issues w.r.t serving files in gzip format over OC.

Your call.

Thank you.

**Closed** 2017-07-30 21:14 UTC
