### ISSUE TITLE
oc.require() triggers callback when dependency is still not loaded

### ISSUE THREAD

**Issue by victorborshak** [opentable/oc#281] opened 2016-08-18 16:30 UTC
When debugging some components on a really slow connection (throttled down to GRPS with disabled cache in Chrome) I noticed that oc.require() triggers the callback in around 2 seconds regardless of whether or not the dependency has been loaded.
I believe this happens because of hardcoded timeout value of 7e3 in head.load.js
https://github.com/opentable/oc/blob/master/src/components/oc-client/src/head.load.js#L501

I believe this value is too small and should be increased to at lease 30 seconds (or a minute) or so.

**Comment by matteofigus** [comment] 2016-08-30 16:12
Hi @victorborshak thanks for your feedback. We use head.js for that and I am not happy about the fact that it seems not really up-to-date and actively maintained.

In that regards, I would prefer, instead of hacking on the head.js, to evaluate a migration to a better supported dependency loader system.

I personally love [SystemJS](https://github.com/systemjs/systemjs) but I would like other contributors' opinion about this, perhaps @mattiaerre @nickbalestra @maxgurewitz @antwhite @chriscartlidge

I list here some of the currently supported functionalities, that we may want to re-discuss:
- Possibility to both load JS or CSS with a callback
- Support for IE8
- Small so that it can be part of the `client.js` without impacting significantly to its size
- Licensed with MIT or compatible OSS license

**Comment by matteofigus** [comment] 2016-10-29 17:06
Hi @victorborshak before working on this I would like to have a working failing example so that we can use it - in case - as a foundation for the new system we are gonna put in place to solve the issue.

Would you be able to share some code with a reproducing failing scenario?

**Comment by navamgupta** [comment] 2016-11-22 21:11
@matteofigus how about using lightningjs 

https://github.com/olark/lightningjs/blob/master/README.md

We run into this problem way too often with conflict in libraries or variables in global scope. This could help with that.

**Comment by matteofigus** [comment] 2016-11-23 17:13
@navamgupta lightningjs seems neat, but unfortunately I see no activity on github for the last 5 years - which is practically the same problem I am trying to solve now by replacing head.js.

I think I would be happy to test a couple of tools, but if we could get an example in github, even a simple gist with a conflict example with reproduction steps, trying out different tools would facilitate the problem's resolution as we could use the bugs as foundation to write some tests on the new integration.

**Comment by navamgupta** [comment] 2016-11-23 18:26
Btw this is a bit off topic from Victors question but - Let me think about how I can get an example of that working, its mostly integration with teams on other stack and the most common example is jQuery conflicts. They already have $ defined say 2.1.0  and our component loads 1.7.1. Now assuming their js gets loaded first and our component's comes in later, we end up with 1.7.1 taking over the $ variable.
Now like everyone else we thought that we could just be like 
```
oc.require('cheggJQuery','//cdn.com/libraries/jquery-1.7.1.js',function(jquery) {
          window.cheggJQuery = window.cheggJQuery || $.noConflict();
        });
```

But what ends up happening is a very interesting timing problem. before the callback function is executed (which $ is still 1.7.1, if there are jquery plugins attaching themselves on the consumer side they sometimes end up registering with the 1.7.1 and when noConflict gets executed $ no longer has the plugin instead its in cheggJQuery. When we first ran into this, I was pretty surprised at the possibility of this happening and did some workarounds but as of last week we started running into the same problems (with backbone and _ as well) with another integration partner. 
Hence lightiningjs came forward as a possible solution. I know its been inactive but we do have people using it actively atleast here who are pretty impressed with it. I will continue looking for a more active alternative.

**Comment by mattiaerre** [comment] 2016-12-22 05:48
hello here, I'm jumping on this discussion; what about this:

https://github.com/ded/script.js

I'll try to have a look at it at some point soon.
it looks interesting.

**Comment by navamgupta** [comment] 2017-04-06 00:12
@mattiaerre The Api looks nice and clean. It provides dependency management but I don't see it provide anything from a js conflict avoidance point of view. Which we can just claim that we do not care about :)

**Comment by matteofigus** [comment] 2017-04-07 10:26
Interesting point @navamgupta - I think whatever we decide to go to, we need to find something that helps with conflicts. I think we need to build some kind of shadow dom for our JS.

**Comment by mattiaerre** [comment] 2017-05-10 20:26
@navamgupta looking at this issue it is something related to what we've just done? anything else still outstanding here for us to have a look at?

// cc @matteofigus

**Comment by matteofigus** [comment] 2017-05-30 19:13
I think that give this has been here for ages, we can try to unblock by forking head and amplifying the timeout from 7s to 30s, and then keep this opened for a better migration. Anyone disagrees?

**Comment by mattiaerre** [comment] 2017-05-30 20:49
@matteofigus either way for me is fine but I'd rather just close this issue and see if we encounter the problem again. unless @victorborshak or @navamgupta have got other opinions 😉

**Comment by NapoleanReigns** [comment] 2017-06-19 13:41
Hi guys, any workarounds for this issue ??

Thanks

**Comment by mattiaerre** [comment] 2017-06-19 15:26
@NapoleanReigns @matteofigus I am going to take care of this issue if you don't mind and attempt a PR; I'll keep you posted.

**Comment by mattiaerre** [comment] 2017-06-19 23:57
hi @NapoleanReigns are you able to give us a way to try to reproduce this issue? is this happening w/ CSS and JS? Thanks.

**Comment by mattiaerre** [comment] 2017-06-20 04:21
so I've been able to reproduce this issue locally and it looks like there is no much choice for us as `head.js` fires the callback after a certain timeout and we cannot check if a specific asset has been downloaded or not. we should aim to find another library that does more or less the same and replace `head.js` maintaining the same signature/behavior for `oc.require`; I've found this library and it looks like it has got the same signature:

[https://github.com/malko/l.js](https://github.com/malko/l.js)

// cc @NapoleanReigns @matteofigus

**Comment by matteofigus** [comment] 2017-06-22 16:31
@NapoleanReigns @victorborshak @navamgupta this should be now fixed on the latest version, can you verify?

If the issue persists, we can reopen.

**Closed by matteofigus** 2017-06-22 16:31 UTC
Labels: bug, client-side library
