### ISSUE TITLE
Sharing global client side dependencies

### ISSUE THREAD

**Issue by matthewdavidson** [opentable/oc#407] opened 2017-03-15 13:35 UTC
In a nutshell:
1. We want to externalize a large dependency (`React` & `ReactDOM` in our case but could be any) from OC components for code sharing reasons
2. The host microsite is responsible for shipping these in the html response
3. Components then depend on these from the global scope (ideally using something like [webpack's externals](https://webpack.js.org/configuration/externals/))

This works fine in principal, but it has the side effect of breaking the components `~preview` url. I've created the following repo to help demonstrate the issue -> https://github.com/matthewdavidson/client-side-render-with-external-deps

We _could_ use the [oc require](https://github.com/opentable/oc/wiki/Browser-client#ocrequire-namespace-url-callback) mechanism, but the guide even mentions:

> "This is particularly useful in case we want to use a javascript dependency and we want to load it only if the container does not exposes it on the global scope." 

The question is, how do you facilitate this _and_ get the `~preview` functionality working?

**Comment by matteofigus** [comment] 2017-03-20 00:16
Ok, the issue is:
* server-side rendered A+B script tags guarantees A is done first and B next. If B depends on A, you're ok
* client-side rendered A+B script tags have no guarantee A is gonna be downloaded and executed first, and B next (and ~preview does client-side rendering). That's why sometimes it could work, sometimes it couldn't (it probably depends on network or caches etc). And that's why we built `oc.require`. With oc.require you know you can require A, then B, and it should be guaranteed to be in the correct order and work. 

So, I tried to move your requires to oc.require and it works for me: https://github.com/matthewdavidson/client-side-render-with-external-deps/pull/1

Consider that if you inspect the HTML you should see react and react dom in the <head> of your page. But if you already have them in a page, the require shouldn't happen and it should just execute the callbacks straightaway.

**Comment by matthewdavidson** [comment] 2017-03-20 16:19
Ok so do you folks always make sure and use `oc.require` whenever you use an external dependency? It make complete sense - load order is non deterministic therefore it makes sense to use an async flow. I guess it was just the note in the wiki that threw me off. 

Feel free to close this :). I suspect we'll want to talk about some improvements that could perhaps be made to the `oc-client` component and the functionality it exposes, namely:

1. first class react support (in progress with #392)
2. Improving the `oc.require` api to use promises or something a little more akin to `import()` (see https://webpack.js.org/guides/code-splitting-import/#dynamic-import)
3. Having the option to drop jquery as we are deprecating it

**Comment by matteofigus** [comment] 2017-03-21 20:48
Ok @matthewdavidson 

1) Can you improve the wiki? Feel free to edit as you like.
2) We will definitely talk more about explicitly declaring client-side deps. This is needed for isomorphic react apps and I know @nickbalestra has a lot of ideas about it. Leave it to me, we'll probably create a whole repo to discuss the react thing very soon.
3) I think browser client needs some love. There is an open discussion about improving the dynamic imports: #281 - if we can improve it on the client or in the bundled js, either is a win!
4) Dropping jquery is complicated when supporting old browsers but I definitely would like to. Perhaps we can start a separate thread to figure out if we want/can drop ie9 support which I think needs a lot of jquery? Feel free to open an issue for that.
5) Closing this as you recommended. Let's discuss the various points in the separate issues.

**Closed by matteofigus** 2017-03-21 20:48 UTC
Labels: client-side library, question
