### ISSUE TITLE
option to set component href to baseURL or use current host

### ISSUE THREAD

**Issue by debopamsengupta** [opentable/oc#427] opened 2017-03-31 15:33 UTC
hi @matteofigus , 

we updated our oc registry and the preview page is broken for us because of https://github.com/opentable/oc/pull/413

We do not use private & public instances, instead our set up is multiple hosts fronted by a single URL. So, this causes issues for us with clashes between protocols (https for the single URL and http for the hosts) 
Would it be possible to add an option in the registry conf to switch between old and new behaviour ?

cc @matthewdavidson @ferewuz

**Comment by matteofigus** [comment] 2017-03-31 16:01
Hi @debopamsengupta - quick question.

So I assume you may have 
* https://publicregistry.com (a)
* http://registry1.private.com (b)
* http://registry2.private.com (c)

where BaseUrl == (a)?

if I correctly understand, when opening
https://(a) the preview should open //(a) and it should work
http://(b) the preview should open //(b) and should work

What is of those steps that I am misunderstanding?

**Comment by debopamsengupta** [comment] 2017-03-31 20:38
Hi @matteofigus ,

What we have is
 - http://registry1.private.com (a)
 - http://registry2.private.com (b)

and https://registry.public.com proxying to (a) or (b) , so the `/~preview` tries to open //(a) or //b from the public URL and fails

**Comment by matteofigus** [comment] 2017-04-01 17:50
I see. So in your case the problem is the protocol.

I wonder if we can make this a bit simpler, like making the page to automatically understand which url is the right one (base url or host) and make the decision for you.

Maybe I'll do a spike in that regard. One strategy could be to make a server-side req to baseUrl and see if we receive a 200 html - so that we could use that - or failover to host in case it returns application/json. Or vice versa.

**Comment by debopamsengupta** [comment] 2017-04-03 08:29
Hi @matteofigus ,

That might be good too, we'd be happy to make PRs for this well once we have a specific approach in mind :)

**Comment by matteofigus** [comment] 2017-04-05 23:22
Thanks @debopamsengupta - given I am doing the spike I can just rather attempt a PR myself, and then perhaps ask you to review if you can?

**Comment by matteofigus** [comment] 2017-04-07 10:24
Fixed by #443

**Closed by matteofigus** 2017-04-07 10:24 UTC
Labels: bug, web-interface
